version: '3'
services:
  homenetmon:
    container_name: homenetmon
    build: .
    restart: unless-stopped
    volumes:
      - homenetmon-data:/data
    network_mode: host
    environment:
      - DEBUG=true
volumes:
  homenetmon-data: